name: Release – SQLite DBs (Policies & Store)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Build project and export SQLite DBs
        run: |
          # Build and export policies database
          ./gradlew :generator:build --quiet
          ./gradlew :generator:jvmRun \
            -DmainClass=io.github.kdroidfilter.database.generator.SqlLiteExtractorKt \
            --quiet
          ls -l generator/build/policies.db

          # Build and export store database
          ./gradlew :storegenerator:build --quiet
          ./gradlew :storegenerator:jvmRun \
            -DmainClass=io.github.kdroidfilter.database.storegenerator.SqliteStoreBuilderKt \
            --quiet
          ls -l storegenerator/build/store-database.db

      - name: Define release name
        id: relname
        run: echo "RELEASE_NAME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git fetch --prune 
          git tag "${{ env.RELEASE_NAME }}" "${{ github.sha }}"
          git push origin "${{ env.RELEASE_NAME }}"

      - name: Create GitHub release and upload artifacts
        uses: softprops/action-gh-release@v2.1.0

        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            generator/build/policies.db
            storegenerator/build/store-database.db
